# Generated by Django 5.2.4 on 2025-07-27 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('can_view', 'Can view users'), ('can_create', 'Can create users'), ('can_edit', 'Can edit users'), ('can_delete', 'Can delete users')]},
        ),
    ]
